### ISSUE TITLE
Tensorflow version error

### ISSUE THREAD

**Issue by pezy** [tperol/ConvNetQuake#1]
When installing the dependencies, I get an error as following:

```sh
Collecting tensorflow==0.11.0rc1 (from -r requirements.txt (line 15))
  Could not find a version that satisfies the requirement tensorflow==0.11.0rc1 (from -r requirements.txt (line 15)) (from versions: 0.12.0rc0, 0.12.0rc1, 0.12.0, 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0)
No matching distribution found for tensorflow==0.11.0rc1 (from -r requirements.txt (line 15))
```

Can I use the newest version of Tensorflow to run this repo, such as TensorFlow 1.2rc0 ?

**Comment by txpdev** [comment]
This repo works with a tensorflow version lower than 1.0. You will need to install this tensorflow version by following the instructions on their website. Hope this help.

**Comment by pezy** [comment]
Thanks.

**Comment by jamesaud** [comment]
Hello,

Will tensorflow version  0.12.1   work?

**Comment by jamesaud** [comment]
Hi, can someone post a link where to install tensorflow 0.11.0rc1? I can find 0.11.0 here:

https://github.com/tensorflow/tensorflow/tree/r0.11

but I am unsure if it is rc1, and I don't think the code was working correctly with version 0.12.1
