### ISSUE TITLE
runtests.sh

### ISSUE THREAD

**Issue by ammaralali** [tperol/ConvNetQuake#2]
As I run the test (runtests.sh), I get an error with py.test
Is this due to the TensorFlow version I'm using (1.2) ?

"
usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: --cov=quakenet
  inifile: None
  rootdir: ~/ConvNetQuake\
"

**Comment by ghost** [comment]
probably you need to : pip install pytest-cov

**Comment by txpdev** [comment]
@ammaralali, sorry for the late response. The unit tests have not been written. Also the code is written for tf 0.10.
