### ISSUE TITLE
Data can't be downloaded

### ISSUE THREAD

**Issue by jamesaud** [tperol/ConvNetQuake#3]
Hello,

Unfortunately dropbox won't let users download folders over a certain size. I get the error 'The zip file is too large'.

It would be much appreciated if you could zip everything into one zip file, and then upload it to Dropbox! I don't think there is a restriction on file size for 1 file, only for folders.

Thanks!

**Comment by jackymallett** [comment]
Alternately, if you can split the contents of the streams folder into smaller folders < 20gb this will also solve the issue.

cf. https://www.dropbox.com/en/help/desktop-web/download-entire-folders?_locale_specific=en
